### ISSUE TITLE
Changer le style de la barre de recherche

### ISSUE THREAD

**Issue by Liritt** [PaulBayfield/Better-IUT-RCC#47]
![image](https://github.com/PaulBayfield/Better-IUT-RCC/assets/110486250/a3484afd-2489-4c95-ba7f-6c8f223c4cfb)
On voit pas la barre de recherche, il faudrait modifier le fond au moins pour qu'on puisse la voir

**Comment by PaulBayfield** [comment]
Je modifie le CSS dans la journée, merci pour le retour 😀

**Comment by PaulBayfield** [comment]
Modification disponible dans la prochaine version.

![image](https://github.com/PaulBayfield/Better-IUT-RCC/assets/137620008/47c497e7-8710-465c-a093-cf26e387e559)
![image](https://github.com/PaulBayfield/Better-IUT-RCC/assets/137620008/2a4ddb33-4780-403c-929d-a4b574016c16)
