### ISSUE TITLE
Fix les messages dans le dark mode

### ISSUE THREAD

**Issue by PolaireP** [PaulBayfield/Better-IUT-RCC#49]
Le texte des messages envoyés par les profs ne sont pas lisible avec le mode sombre
![Capture d'écran 2024-06-24 153015](https://github.com/PaulBayfield/Better-IUT-RCC/assets/130983707/f59c9a72-4d0a-4e3a-b0dc-5f1d7879e627)

**Comment by PaulBayfield** [comment]
C'est corrigé ou pas @simon511000 ? Si non, je peux m'en occuper si tu veux ?

**Comment by PaulBayfield** [comment]
@PolaireP corrigé dans la prochaine version, merci pour le signalement !
