### ISSUE TITLE
Notifications pour des nouvelles notes

### ISSUE THREAD

**Issue by PaulBayfield** [PaulBayfield/Better-IUT-RCC#52]
Notification lors de l'apparition des nouvelles notes.

- **Style de notification** : à définir
- **Implémentation** :  

Modification du manifest avec l'ajout du script.
```json
"background": {
    "service_worker": "background.js",
    "type": "module"
},
```
Tâche de fond qui compare les notes sauvegardées et les nouvelles notes.
- **Rafraichissement** : à définir, 1h peut être ?

**Comment by PaulBayfield** [comment]
Il faut aussi vérifier l'authentification. L'utilisateur doit se reconnecter souvent, ça limite la fonctionnalité 🤔

**Comment by PaulBayfield** [comment]
L'idée est intéressante mais très compliqué à mettre en place. Le token de session expire de temps en temps, on pourrait sauvegarder le mot de passer & login de l'utilisateur puisque tout reste en local mais il ne serait pas crypté...

Je garde l'issue ouvert si quelqu'un veut proposer quelque chose.

**Comment by PaulBayfield** [comment]
Impossible sans un backend, problème de CORS...

**Comment by PaulBayfield** [comment]
Problèmes de CORS résolus, l'extension peut désormais récupérer les notes en arrière plan !

![image](https://github.com/PaulBayfield/Better-IUT-RCC/assets/137620008/27534785-1ba7-4536-8007-b21b4b76ab05)

**Comment by simon511000** [comment]
T'es trop un BG Paul

**Comment by PaulBayfield** [comment]
✅ Ajouté : https://github.com/PaulBayfield/Better-IUT-RCC/pull/54
